### ISSUE TITLE
`impl Error for DecodeError`?

### ISSUE THREAD

**Issue by soumya92** [decafbad/z85#3]
Coming from 2.x, where `ParserError` implemented `std::error::Error`, I was surprised to see that the new `DecodeError` implements a lot less.

It would be nice to have the same traits implemented for `DecodeError` (`Error`, `Display`, `Eq`, etc.). Is that something that sounds reasonable? Or is there a reason for dropping those traits?

**Comment by decafbad** [comment]
You are right. I'm on it.

**Comment by decafbad** [comment]
Fixed in 3.0.2
