### ISSUE TITLE
Decoding fails for some input strings

### ISSUE THREAD

**Issue by ghost** [decafbad/z85#4]
If the input string's length is not a multiple of five, the decoding fails with a `DecodeError(InvalidLength)`.

**Comment by ghost** [comment]
https://github.com/decafbad/z85/blob/ca669a0682b0a559b883f770c93e746f6a7e3ebe/src/lib.rs#L83

This probably has a better solution.

**Comment by decafbad** [comment]
That's expected behavior. It's what the RFC I implemented states.

**Comment by ghost** [comment]
Yeah, I also found that out somewhere else. 

It seems those slackers who make the online z85 encoders just swap out the base85 alphabet without much thinking about the RFC specification.
